project:
  type: website
  output-dir: docs

website:
  title: "ProjetR"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: qmd/report.qmd
        text: Rapport

format:
  html:
    theme: cosmo
    toc: true
